apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: davibmmgallo/current-time:v1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api 
spec:
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 8080
      nodePort: 30000
  type: NodePort